#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
npm run lint ||
(
        echo '❌ ESLint Check Failed 
                Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run ts.check ||
(
    echo '❌ Failed Type check.
            Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Build failed ❌👷🔨❌
            Build failed: View the errors above to see why. 
    '
    false;
)

git add .

# If everything passes... Now we can commit
echo '✅✅✅✅ You have won... I am committing this now. ✅✅✅✅'